[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/",
]

# For deployment
fs_permissions = [{ access = "read-write", path = "./"}]

unknown_chain = { key = "Lw04kWVLYWpQRLelp5KTNWscih06Mkti", chain = 1, url = "https://virtual.mainnet.rpc.tenderly.co/06429f16-41e8-42d5-942c-cc7a421269dc" }